SELECT state FROM healthcare_stats ORDER BY anaemia_female DESC LIMIT 1;
SELECT state FROM healthcare_stats ORDER BY anaemia_male ASC LIMIT 1;
SELECT AVG(vaccination_rate) FROM healthcare_stats;
SELECT state FROM healthcare_stats WHERE vaccination_rate < 70;
SELECT state FROM healthcare_stats ORDER BY obesity_rate DESC LIMIT 1;
SELECT state FROM healthcare_stats ORDER BY obesity_rate ASC LIMIT 1;
SELECT state FROM healthcare_stats WHERE diabetes_rate > 10;
SELECT AVG(diabetes_rate) FROM healthcare_stats WHERE area_type='Urban';
SELECT AVG(diabetes_rate) FROM healthcare_stats WHERE area_type='Rural';
SELECT state FROM healthcare_stats ORDER BY asthma_rate DESC LIMIT 1;
SELECT state FROM healthcare_stats WHERE asthma_rate < 5;
SELECT state FROM healthcare_stats ORDER BY hypertension_rate DESC LIMIT 1;
SELECT AVG(hypertension_rate) FROM healthcare_stats;
SELECT state FROM healthcare_stats WHERE hypertension_rate > (SELECT AVG(hypertension_rate) FROM healthcare_stats);
SELECT state FROM healthcare_stats ORDER BY cancer_rate DESC LIMIT 1;
SELECT state FROM healthcare_stats WHERE cancer_rate < 1;
SELECT AVG(anaemia_female) FROM healthcare_stats WHERE area_type='Rural';
SELECT AVG(anaemia_female) FROM healthcare_stats WHERE area_type='Urban';
SELECT state FROM healthcare_stats WHERE anaemia_male > anaemia_female;
SELECT state FROM healthcare_stats ORDER BY ABS(anaemia_female - anaemia_male) DESC LIMIT 1;
SELECT state FROM healthcare_stats WHERE obesity_rate > diabetes_rate;
SELECT state FROM healthcare_stats ORDER BY vaccination_rate ASC LIMIT 1;
SELECT state FROM healthcare_stats WHERE vaccination_rate > 90;
SELECT AVG(asthma_rate) FROM healthcare_stats WHERE area_type='Urban';
SELECT AVG(asthma_rate) FROM healthcare_stats WHERE area_type='Rural';
SELECT state FROM healthcare_stats ORDER BY maternal_mortality_rate DESC LIMIT 1;
SELECT state FROM healthcare_stats WHERE maternal_mortality_rate > 100;
SELECT AVG(maternal_mortality_rate) FROM healthcare_stats;
SELECT state FROM healthcare_stats ORDER BY maternal_mortality_rate ASC LIMIT 1;
SELECT DISTINCT h1.state FROM healthcare_stats h1 WHERE h1.area_type='Rural' AND h1.hypertension_rate > (SELECT h2.hypertension_rate FROM healthcare_stats h2 WHERE h2.state=h1.state AND h2.area_type='Urban');
SELECT state FROM healthcare_stats ORDER BY (anaemia_female + anaemia_male) DESC LIMIT 1;
SELECT state FROM healthcare_stats WHERE obesity_rate < 5;
SELECT AVG(obesity_rate) FROM healthcare_stats WHERE area_type='Urban';
SELECT AVG(obesity_rate) FROM healthcare_stats WHERE area_type='Rural';
SELECT state FROM healthcare_stats WHERE diabetes_rate < asthma_rate;
SELECT state FROM healthcare_stats WHERE area_type='Rural' ORDER BY vaccination_rate DESC LIMIT 1;
SELECT state FROM healthcare_stats WHERE area_type='Urban' ORDER BY vaccination_rate DESC LIMIT 1;
SELECT state FROM healthcare_stats WHERE anaemia_female > 50;
SELECT state FROM healthcare_stats WHERE anaemia_male < 20;
SELECT state FROM healthcare_stats ORDER BY cancer_rate ASC LIMIT 1;
